# 网址
# console.d.run

# 账号 密码
# uncledou@qq.com
# Zaowu806.

# 单图训练（Lora)
export HF_HOME=huggingface
export HF_ENDPOINT='https://hf-mirror.com'
/root/miniconda3/bin/accelerate launch --main_process_port 26188 --dynamo_backend no --dynamo_mode default --gpu_ids 0 --mixed_precision bf16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 /root/data-local/train/autodl-tmp/kohya_ss/sd-scripts/flux_train_network.py --output_dir "/root/data-local/inference/ComfyUI/models/loras/flux-bf" --logging_dir  "/root/data-local/dataset/log/bf0509flux" --max_train_epochs 6 --learning_rate 1 --output_name "北服_汉女single_picture_test_1e-6" --save_every_n_epochs 1 --save_precision bf16 --seed 1026 --max_token_length 225 --caption_extension ".txt" --vae_batch_size 4  --clip_l /root/data-local/inference/ComfyUI/models/clip/clip_l.safetensors --t5xxl /root/data-local/inference/ComfyUI/models/clip/t5xxl_fp8_e4m3fn.safetensors --timestep_sampling sigma --model_prediction_type raw --guidance_scale 1 --ae /root/data-local/inference/ComfyUI/models/vae/ae.sft --cache_text_encoder_outputs --cache_text_encoder_outputs_to_disk --sdpa --train_data_dir "/root/data-local/dataset/picture50" --train_batch_size 1 --resolution=1024,1024 --enable_bucket --min_bucket_reso 256 --max_bucket_reso 2048 --bucket_reso_steps 64 --network_args split_qkv=True --pretrained_model_name_or_path /root/data-local/inference/ComfyUI/models/unet/flux1-dev-fp8_unet.safetensors --save_model_as safetensors --clip_skip 1 --network_dim 96 --network_alpha 48  --persistent_data_loader_workers --cache_latents --cache_latents_to_disk --gradient_checkpointing --optimizer_type=Prodigy --unet_lr 1 --text_encoder_lr 1 --mixed_precision bf16 --gradient_accumulation_steps=1 --network_module=networks.lora_flux  --lr_scheduler=linear --fp8_base --lr_warmup_steps 10 --lr_decay_steps=10 --sample_every_n_epochs=1 --sample_prompts="/root/data-local/dataset/picture50/100_汉女/HFQJ-1.txt" --sample_sampler="euler_a" --logging_dir "/root/data-local/dataset/log/bf0509flux/100_汉女"

# 单图训练（Dreambooth）
export HF_HOME=huggingface
export HF_ENDPOINT='https://hf-mirror.com'
/root/miniconda3/bin/accelerate launch --main_process_port 28888 --dynamo_backend no --dynamo_mode default --gpu_ids 0 --mixed_precision bf16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 /root/data-local/train/autodl-tmp/kohya_ss/sd-scripts/flux_train.py --pretrained_model_name_or_path /root/data-local/train/autodl-tmp/kohya_ss/models/unet/flux1-dev_unet.safetensors --clip_l /root/data-local/inference/ComfyUI/models/clip/clip_l.safetensors --t5xxl /root/data-local/inference/ComfyUI/models/clip/t5xxl_fp16.safetensors --ae /root/data-local/inference/ComfyUI/models/vae/ae.sft --resolution "1024,1024" --enable_bucket --min_bucket_reso 256 --max_bucket_reso 2048 --bucket_reso_steps 64 --train_data_dir "/root/data-local/dataset/picture50" --caption_extension ".txt" --learning_rate 3e-6 --max_train_epochs 6 --save_every_n_epochs 6 --seed 42 --max_data_loader_n_workers 2 --persistent_data_loader_workers --optimizer_type adafactor --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False" --lr_scheduler warmup_stable_decay --lr_warmup_steps 200 --lr_decay_steps 0.25 --gradient_checkpointing --mixed_precision bf16 --save_precision bf16 --highvram --cache_latents_to_disk --save_model_as safetensors --output_dir "/root/data-local/inference/ComfyUI/models/unet" --output_name 北服_汉女single_picture_test_3e-6 --sdpa --timestep_sampling flux_shift --discrete_flow_shift 3.1582 --model_prediction_type raw --fused_backward_pass --max_grad_norm 1.0 --sample_prompts "/root/data-local/dataset/picture50/100_汉女/HFQJ-1.txt" --sample_sampler "euler_a" --logging_dir "/root/data-local/dataset/picture50/100_汉女_3e-6" --train_batch_size 1 --sample_every_n_epochs 1 --t5xxl_max_token_length 512
